# Basic
title: JaneVia's Blog
subtitle: If Not Me, Who? If Not Now, When?
welcome_message: <a href="https://janevia.github.io/" target="_blank">Download the theme</a>
description: Welcom to my blog.
creator: <a href="https://janevia.github.io">@onevcat</a>

url: "https://janevia.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://janevia.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: janevia
    github: janevia
    twitter: janevia
    gplus: 
    mail: imzhangweiyang@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
